### ISSUE TITLE
Supreme Monitor Link Incorrect

### ISSUE THREAD

**Issue by redtoothpaste** [yasserqureshi1/Sneaker-Monitors#104]
**Describe the bug**
When Supreme monitor sends webhook to Discord, the link redirects to the base Supreme webpage instead of the item page. 

**To Reproduce**
1. Supreme restocks an item
2. Monitor sends webhook to Discord
3. Click the link on webhook
4. Launches on Supreme's splash page instead of item page

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: macOS 12.0 Beta
 - Browser: Chrome and Safari

**Additional context**
- I noticed that the link is ("https://www.supremenewyork.com/shop/{item_id}") when it should contain more information.
- From another monitor I used their redirect link is ("https://www.supremenewyork.com/shop/accessories/sb18zu4oh/hp843qfb5") while yours is ("https://www.supremenewyork.com/shop/174389") and it doesnt route correctly. 
- Other than that it has been amazing! Thank you!
- Would be cool to have the link be selectable to different web broswers!

**Comment by yasserqureshi1** [comment]
Fixed
