### ISSUE TITLE
Error running

### ISSUE THREAD

**Issue by Doitagain187** [yasserqureshi1/Sneaker-Monitors#107]
Payload delivered successfully, code 204.
Traceback (most recent call last):
  File "C:\Users\ssk\Desktop\Python\Bot development\Seleinum\Sneaker-Monitors-master\SNKRS\SNKRSMonitor.py", line 233, in <module>
    monitor()
  File "C:\Users\ssk\Desktop\Python\Bot development\Seleinum\Sneaker-Monitors-master\SNKRS\SNKRSMonitor.py", line 187, in monitor
    items = scrape_site(proxy=proxy, headers=headers)
  File "C:\Users\ssk\Desktop\Python\Bot development\Seleinum\Sneaker-Monitors-master\SNKRS\SNKRSMonitor.py", line 41, in scrape_site
    for item in output['objects']:
KeyError: 'objects'

How do i fix this?

**Comment by Doitagain187** [comment]
Exception found: Traceback (most recent call last):
  File "C:\Users\ssk\Desktop\Python\Premade\Sneaker-Monitors-master\SNKRS\SNKRSMonitor.py", line 189, in monitor    
    for j in item['productInfo']:
KeyError: 'productInfo'

**Comment by yasserqureshi1** [comment]
> Payload delivered successfully, code 204.
> 
> Traceback (most recent call last):
> 
>   File "C:\Users\ssk\Desktop\Python\Bot development\Seleinum\Sneaker-Monitors-master\SNKRS\SNKRSMonitor.py", line 233, in <module>
> 
>     monitor()
> 
>   File "C:\Users\ssk\Desktop\Python\Bot development\Seleinum\Sneaker-Monitors-master\SNKRS\SNKRSMonitor.py", line 187, in monitor
> 
>     items = scrape_site(proxy=proxy, headers=headers)
> 
>   File "C:\Users\ssk\Desktop\Python\Bot development\Seleinum\Sneaker-Monitors-master\SNKRS\SNKRSMonitor.py", line 41, in scrape_site
> 
>     for item in output['objects']:
> 
> KeyError: 'objects'
> 
> 
> 
> 
> 
> How do i fix this?

This error occurs because the monitor is unable to access the site. This is usually because the location and language variables are not set properly

**Comment by yasserqureshi1** [comment]
> Exception found: Traceback (most recent call last):
> 
>   File "C:\Users\ssk\Desktop\Python\Premade\Sneaker-Monitors-master\SNKRS\SNKRSMonitor.py", line 189, in monitor    
> 
>     for j in item['productInfo']:
> 
> KeyError: 'productInfo'
> 
> 

See #106

**Comment by Doitagain187** [comment]
Actually, i figured out theres an issue with bots on my computer accessing SNKRS. I bought TheShitBot yesterday and it cant verify my nike accounts. Any suggestions?

Also, i triple checked the location and settings and stuff

**Comment by yasserqureshi1** [comment]
> Actually, i figured out theres an issue with bots on my computer accessing SNKRS. I bought TheShitBot yesterday and it cant verify my nike accounts. Any suggestions?
> 
> Also, i triple checked the location and settings and stuff
> > On Sep 11, 2021, at 12:44 PM, Yasser Qureshi ***@***.***> wrote:
> > 
> > ﻿
> > Payload delivered successfully, code 204.
> > 
> > Traceback (most recent call last):
> > 
> > File "C:\Users\ssk\Desktop\Python\Bot development\Seleinum\Sneaker-Monitors-master\SNKRS\SNKRSMonitor.py", line 233, in
> > 
> > monitor()
> > File "C:\Users\ssk\Desktop\Python\Bot development\Seleinum\Sneaker-Monitors-master\SNKRS\SNKRSMonitor.py", line 187, in monitor
> > 
> > items = scrape_site(proxy=proxy, headers=headers)
> > File "C:\Users\ssk\Desktop\Python\Bot development\Seleinum\Sneaker-Monitors-master\SNKRS\SNKRSMonitor.py", line 41, in scrape_site
> > 
> > for item in output['objects']:
> > KeyError: 'objects'
> > 
> > How do i fix this?
> > 
> > This error occurs because the monitor is unable to access the site. This is usually because the location and language variables are not set properly
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> > Triage notifications on the go with GitHub Mobile for iOS or Android. 
> 

So the monitor tries to access the following site. Could you try paste it into a browser and see what pops up? It should be a JSON document (basically looks like a plain text document). 

https://api.nike.com/product_feed/threads/v2/?anchor=0&count=60&filter=marketplace%28GB%29&filter=language%28en-GB%29&filter=channelId%28010794e5-35fe-4e32-aaff-cd2c74f89d61%29&filter=exclusiveAccess%28true%2Cfalse%29&fields=active%2Cid%2ClastFetchTime%2CproductInfo%2CpublishedContent.nodes%2CpublishedContent.subType%2CpublishedContent.properties.coverCard%2CpublishedContent.properties.productCard%2CpublishedContent.properties.products%2CpublishedContent.properties.publish.collections%2CpublishedContent.properties.relatedThreads%2CpublishedContent.properties.seo%2CpublishedContent.properties.threadType%2CpublishedContent.properties.custom%2CpublishedContent.properties.title

**Comment by Doitagain187** [comment]
On Saturday, September 11, 2021, 01:17:17 PM PDT, Yasser Qureshi ***@***.***> wrote:  
 
 



Actually, i figured out theres an issue with bots on my computer accessing SNKRS. I bought TheShitBot yesterday and it cant verify my nike accounts. Any suggestions?

Also, i triple checked the location and settings and stuff


On Sep 11, 2021, at 12:44 PM, Yasser Qureshi @.***> wrote:

﻿
Payload delivered successfully, code 204.

Traceback (most recent call last):

File "C:\Users\ssk\Desktop\Python\Bot development\Seleinum\Sneaker-Monitors-master\SNKRS\SNKRSMonitor.py", line 233, in

monitor()
File "C:\Users\ssk\Desktop\Python\Bot development\Seleinum\Sneaker-Monitors-master\SNKRS\SNKRSMonitor.py", line 187, in monitor

items = scrape_site(proxy=proxy, headers=headers)
File "C:\Users\ssk\Desktop\Python\Bot development\Seleinum\Sneaker-Monitors-master\SNKRS\SNKRSMonitor.py", line 41, in scrape_site

for item in output['objects']:
KeyError: 'objects'

How do i fix this?

This error occurs because the monitor is unable to access the site. This is usually because the location and language variables are not set properly

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.



So the monitor tries to access the following site. Could you try paste it into a browser and see what pops up? It should be a JSON document (basically looks like a plain text document).

https://api.nike.com/product_feed/threads/v2/?anchor=0&count=60&filter=marketplace%28GB%29&filter=language%28en-GB%29&filter=channelId%28010794e5-35fe-4e32-aaff-cd2c74f89d61%29&filter=exclusiveAccess%28true%2Cfalse%29&fields=active%2Cid%2ClastFetchTime%2CproductInfo%2CpublishedContent.nodes%2CpublishedContent.subType%2CpublishedContent.properties.coverCard%2CpublishedContent.properties.productCard%2CpublishedContent.properties.products%2CpublishedContent.properties.publish.collections%2CpublishedContent.properties.relatedThreads%2CpublishedContent.properties.seo%2CpublishedContent.properties.threadType%2CpublishedContent.properties.custom%2CpublishedContent.properties.title

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
