### ISSUE TITLE
NOT ABLE TO INSTALL SNKRS MONITOR

### ISSUE THREAD

**Issue by Dhruv3000** [yasserqureshi1/Sneaker-Monitors#112]
from random_user_agent.params import SoftwareName, HardwareType
ModuleNotFoundError: No module named 'random_user_agent SHOWS THIS ERROR

**Comment by cens6r** [comment]
Install the random_user_agent module: pip install random-user-agent

**Comment by kacperkwapisz** [comment]
This issue seems to be resolved.

Solution: `pip install random-user-agent` or `pip3 install random-user-agent`

Closing this issue for now!
