### ISSUE TITLE
SNKRS Monitor - bug?

### ISSUE THREAD

**Issue by singh763173** [yasserqureshi1/Sneaker-Monitors#117]
Not sure if this is a bug or not, but will leave the monitor to run for some time - raising just in case it's a problem

when running the monitor, it posts it's test successfully but the script continues to output:

Anchor 60
Anchor 120
Anchor 180

Is this normal?

**Comment by xyn23** [comment]
I got same issue

**Comment by kacperkwapisz** [comment]
Hello, no it is not. Did you change something in the source code of the monitor?

**Comment by king1267** [comment]
> Hello, no it is not. Did you change something in the source code of the monitor?

Hi, I'm having the same issue. The only thing I changed was the info in the .env file such as the webhook, location, loc, and lan.

**Comment by yasserqureshi1** [comment]
Actually this is normal behaviour. So it monitors the top 180 most recent products. This is because you can only request for 60 products at a time so to ensure speed and lower the number of requests, I chose 180. So it prints the anchor for every api call it makes.
