### ISSUE TITLE
Proxies aren't working, fails silently and defaults to regular IP

### ISSUE THREAD

**Issue by delamae** [yasserqureshi1/Sneaker-Monitors#118]
ShopifyMonitor.py works fine without proxy, actually it works with the proxies too but the regular IP leaks.

The .env has 10 proxies, looks like
`PROXY = 'username:asdf123asdf123@108.106.101.26:7878%username:asdf123asdf123@108.106.101.26:7878'
`
I tested all the proxies manually in my browser and it properly resolves to the remote IP.

Sounds similar to this user who also was using a proxy and got his main IP banned
https://github.com/yasserqureshi1/Sneaker-Monitors/issues/29#issuecomment-755047838

Using Lubuntu 20.04 desktop, Python 3.8.10

Any suggestions?

**Comment by kacperkwapisz** [comment]
Hello, did you really mean `ShopifyMonitor.js` or is it just a typo?

**Comment by delamae** [comment]
Hah, good point, I meant .py.

**Comment by yasserqureshi1** [comment]
I think it was my fault - I think the proxy was passed wrong. It should be fixed now. Here's a similar [issue](https://stackoverflow.com/questions/25828217/python-requests-with-proxy-not-working-leaking-ip)
