### ISSUE TITLE
How to bypass geetest when monitoring footsites (other sites with Datadome protection)

### ISSUE THREAD

**Issue by 2YOU2HOU2** [yasserqureshi1/Sneaker-Monitors#119]
Thank you for sharing the code but when I create my own monitor on https://www.hermes.com which should be the same as footsites protect by Datadome and need to solve geetest after certain requests. Any suggestion to bypass or autosolve it?

**Comment by kacperkwapisz** [comment]
Hello, this issue is not related to the repo. 
Please join the official discord server of this repo by using this link: https://discord.gg/EqM2Cu9ymt
There might be people that can help you achieve what you want to!

**Comment by kacperkwapisz** [comment]
If anything is going on with the monitors available in this repo, please create a new issue.

I will close this issue then!
