### ISSUE TITLE
Is the code invalid?

### ISSUE THREAD

**Issue by aimeikong** [yasserqureshi1/Sneaker-Monitors#126]
Hello! I used your code about snkrs on the GitHub website. After running for a period of time, I found that I often couldn't grab the updated products.
Is the code invalid? Can you help add the code to control the crawling frequency, such as crawling the snkrs website every 1800 seconds?

**Comment by yasserqureshi1** [comment]
The code is fine. Within the scripts you will find `time.sleep(X)`. Change `X` to the 1800
