### ISSUE TITLE
hi everytime i try to install the requirements it says the same error

### ISSUE THREAD

**Issue by guga040** [yasserqureshi1/Sneaker-Monitors#128]
error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
  
  
  
  I already tried to update the tools and the pip and i get the same error when installing the requirements

**Comment by yasserqureshi1** [comment]
Try `pip install --upgrade setuptools` and also do `pip install wheel`
