### ISSUE TITLE
SNKRS and Supreme

### ISSUE THREAD

**Issue by WTFisthisusername** [yasserqureshi1/Sneaker-Monitors#129]
The SNKRS and Supreme monitors as well as the other monitors (offspring etc) don't work. The only monitors that do work is the Shopify one and FootlockerUK, rest don't work and say error when started.

**Comment by yasserqureshi1** [comment]
What is the error? I've checked them and they're working fine

**Comment by yasserqureshi1** [comment]
Fixed them
