### ISSUE TITLE
Trouble getting in to the Sneakers-Monitors-master directory via the Command Prompt.. 

### ISSUE THREAD

**Issue by sBach98** [yasserqureshi1/Sneaker-Monitors#130]
Hi Yasser, i'm trying to set up the Sneaker Monitor. after i installed all the Python and pip stuff im trying to acces the Sneaker-monitors-master after I downloaded it via Github. When I'm inside the folder where I saved the folder and want to acces the folder i get the error "The system cannot find the path specified"... Do you have any idea how to fix this? 
![Screenshot 2022-04-10 131316](https://user-images.githubusercontent.com/103363647/162615334-3aa1374e-9a22-40fd-afe4-3faf4e8cf47c.png)

**Comment by yasserqureshi1** [comment]
So currently you're in your Documents. It looks like you didn't download the repo there. Navigate to the directory that you downloaded the repo using commands `cd <insert directory name here>` and `cd ..` (to go back a directory).
