### ISSUE TITLE
just a question

### ISSUE THREAD

**Issue by DonXirus** [yasserqureshi1/Sneaker-Monitors#131]
is this means that the bot is connected to discord and working well?

root@root:/home/root/Sneaker-Monitors/SNKRS# python3 SNKRSMonitor.py
STARTING MONITOR
Payload delivered successfully, code 204.
Anchor 60
Anchor 120
Anchor 180
Anchor 60
Anchor 120
Anchor 180
Anchor 60
Anchor 120
Anchor 180
Anchor 60
Anchor 120
Anchor 180

**Comment by yasserqureshi1** [comment]
This is normal behaviour - each anchor denotes the number of products it has scraped. The monitor only looks at the 180 most recent products.
