### ISSUE TITLE
SNKRS MONITOR DOES NOT WORK WITH CHILEAN LOCATION 

### ISSUE THREAD

**Issue by mfj123** [yasserqureshi1/Sneaker-Monitors#135]
I changed the location to Chile
LOCATION="CL"
LANGUAGE="es-419"
But I'm gettin an error that says:

"list indices must be integers or slices, not str line 218"
![image](https://user-images.githubusercontent.com/28930546/170718876-ba0ac438-4738-47c6-b0ca-badedb2d3699.png)

But when i change the config to Spain, the monitor works fine
LOCATION="ES"
LANGUAGE="es-ES"

Both configs returns item from the url generated by the monitor.

https://api.nike.com/product_feed/threads/v3/?anchor=100&count=50&filter=marketplace%28CL%29&filter=language%28es-419%29&filter=channelId%28010794e5-35fe-4e32-aaff-cd2c74f89d61%29&filter=exclusiveAccess%28true%2Cfalse%29

https://api.nike.com/product_feed/threads/v3/?anchor=100&count=50&filter=marketplace%28ES%29&filter=language%28es-ES%29&filter=channelId%28010794e5-35fe-4e32-aaff-cd2c74f89d61%29&filter=exclusiveAccess%28true%2Cfalse%29

but only Spain config works fine.

Please help to correct this error.

Thanks for the monitoring tools.

**Comment by yasserqureshi1** [comment]
New update for Chile location

**Comment by mfj123** [comment]
> New update for Chile location
@yasserqureshi1 
Hi, I already test the chilean location and it's works but i'm getting an error  from the websocket after a few minutes running.
```
websockets.client - < TEXT '{"method":"Target.targetCrashed","params":{"tar...killed","errorCode":9}}' [122 bytes]
pyppeteer.connection.Connection - RECV: {"method":"Target.receivedMessageFromTarget","params":{"sessionId":"4DBCEABEAF504529A30C033EB524ABDB","message":"{\"method\":\"Inspector.targetCrashed\",\"params\":{}}","targetId":"B4DAD37CEFC56A3A1B0D0273F5620469"}}
pyppeteer.connection.CDPSession - RECV: {"method":"Inspector.targetCrashed","params":{}}
websockets.client - = connection is CLOSING
websockets.client - > CLOSE 1000 (OK) [2 bytes]
websockets.client - ! failing connection with code 1006
websockets.client - = connection is CLOSED
```
When this ocurres the only way to continue running it is press Ctrl+C on the terminal, after this the monitor keeps running from another few minutes. So i can't let by it self running, cause need to do this to restart the cycle without terminate the app.
I appreciate your help to catch this event, thank you very much.

PD: You miss the category (SNKRS) parameter "B:2000002" on the URL:
`https://www.nike.cl/api/catalog_system/pub/products/search?fq=B:2000002&_from=0&_to=49`
