### ISSUE TITLE
I keep getting a error when trying to setup the monitor

### ISSUE THREAD

**Issue by bubbbleee1234** [yasserqureshi1/Sneaker-Monitors#138]
I have python installed and everything else I need but after I set up this monitor I keep getting 'something went wrong please check input' when I run it. For some reason, I think my input is right though. Thanks
![Capture](https://user-images.githubusercontent.com/90427682/179618155-025bf993-6610-4fc3-9453-abc326b5b146.PNG)

**Comment by yasserqureshi1** [comment]
I've just sorted this out in this update
