### ISSUE TITLE
URL in discord for nl region

### ISSUE THREAD

**Issue by synta-xerror** [yasserqureshi1/Sneaker-Monitors#14]
Nice work man keep it up! but the url voor the nl region doesnt work little issue

**Comment by yasserqureshi1** [comment]
Thanks. Are you sure you set it up correctly? For the Netherlands, if you want the language in English, ensure that the location and language variables in the `.env` file are set as follows:
`
LOCATION = "NL"
LANGUAGE = "en-GB"
`
Or if you want the language in Dutch:
`
LOCATION = "NL"
LANGUAGE = "nl"
`

Ensure you have set the Webhook url correctly as well. If you are using a VPS or server of any kind, you may need to use a proxy. 

If this persists, please reopen this issue. Thanks

**Comment by synta-xerror** [comment]
Thanks fixed it!
