### ISSUE TITLE
Exception found: Traceback (most recent call last):

### ISSUE THREAD

**Issue by infralise123984** [yasserqureshi1/Sneaker-Monitors#142]
When i run the sneaker monitor with the CL es-419 config  i get this error

![image](https://user-images.githubusercontent.com/113802981/190877127-534f708a-7994-4975-842b-0dd1ec70f3a3.png)

**Comment by yasserqureshi1** [comment]
> When i run the sneaker monitor with the CL es-419 config i get this error
> 
> ![image](https://user-images.githubusercontent.com/113802981/190877127-534f708a-7994-4975-842b-0dd1ec70f3a3.png)

Is this still an issue?

**Comment by VividBeatzYT** [comment]
> > When i run the sneaker monitor with the CL es-419 config i get this error
> > ![image](https://user-images.githubusercontent.com/113802981/190877127-534f708a-7994-4975-842b-0dd1ec70f3a3.png)
> 
> Is this still an issue?

YES IT IS, idek know what "CL es-419 config" is but apparently I have it

**Comment by yasserqureshi1** [comment]
Updated structure should no longer have this issue
