### ISSUE TITLE
Error when try to run

### ISSUE THREAD

**Issue by Marting2105** [yasserqureshi1/Sneaker-Monitors#144]
Hello,
Here is the error I get when I run any monitor.
![image](https://user-images.githubusercontent.com/97480952/200476810-83132555-6441-4848-997b-906228707e3b.png)

**Comment by Marting2105** [comment]
then I got this when I installed py on path 
![image](https://user-images.githubusercontent.com/97480952/200476665-9dffe964-e14b-42f3-8f0c-46396bc3bf8b.png)

**Comment by yasserqureshi1** [comment]
Updated monitor structure shouldnt have this issue
