### ISSUE TITLE
No output from monitors

### ISSUE THREAD

**Issue by fernstedt** [yasserqureshi1/Sneaker-Monitors#148]
I am trying your bots out.

There is no output at all from any monitor to discord. 4 of them are running in screens. 

Logs are building up with json feed but no output at all.

**Comment by yasserqureshi1** [comment]
I believe this was an issue where there was a check for keywords. 
```
KEYWORDS = []

if KEYWORDS is []:
    # do something
```
When it should be....
```
if KEYWORDS == []:
    # do something
```
