### ISSUE TITLE
env

### ISSUE THREAD

**Issue by HamzaShelleh** [yasserqureshi1/Sneaker-Monitors#15]
Hi I finished the installation of requirement's and I'm trying to open the env file but I don't know how to open it also when i try to open the shopify py it closes right away and says site URL incorrect

**Comment by yasserqureshi1** [comment]
Hi. You can open the ```.env``` file in any text editor such as Notepad on Windows.

With the Shopify monitor, the URL has to point to a ```products.json``` file. For example, If I want to have the new items for the Hanon Shop (https://www.hanon-shop.com/collections/whats-new), I put ```products.json``` at the end, like so...
```
URL = "https://www.hanon-shop.com/collections/whats-new/products.json"
```
