### ISSUE TITLE
Multiple sites on Shopify Monitor

### ISSUE THREAD

**Issue by HamzaShelleh** [yasserqureshi1/Sneaker-Monitors#17]
How do I put multiple shopify sites on the monitor

**Comment by yasserqureshi1** [comment]
Currently there is no support for multiple sites. I will update this very shortly though.

**Comment by DarylRob** [comment]
Seconded for this :)

**Comment by yasserqureshi1** [comment]
Main issue with this is that the monitor will be very slow to pick up changes. Instead its best to create another copy of the Python file for the other site and run that separately.
