### ISSUE TITLE
Zalando monitor

### ISSUE THREAD

**Issue by synta-xerror** [yasserqureshi1/Sneaker-Monitors#18]
The zalando monitor gives me this warning:
InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

**Comment by yasserqureshi1** [comment]
Thats a warning, and its not an issue. See #2 for details
