### ISSUE TITLE
connection error

### ISSUE THREAD

**Issue by synta-xerror** [yasserqureshi1/Sneaker-Monitors#19]
Sorry for the amount of questions but  a few monitors give this error: 
HTTPSConnectionPool(host='www.supremenewyork.com', port=443): Max retries exceeded with url: /shop/305604.json (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x758eba70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
 And footlocker gives me this :
There was an Error - main site -  HTTPSConnectionPool(host='www.footlocker.nl', port=443): Read timed out. (read timeout=3)

**Comment by yasserqureshi1** [comment]
I've updated both monitors. Test these out and let me know how they work
