### ISSUE TITLE
SSl bug

### ISSUE THREAD

**Issue by Leon-AroundMedia** [yasserqureshi1/Sneaker-Monitors#2]
Hello,

Nice scripts/bot's. I get an error while trying to start the SNKRS monitor:

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

Did I something wrong?

**Comment by yasserqureshi1** [comment]
Nope this is just a warning not an error. It makes unverified requests, so does not verify the target server’s SSL Certificate. This is not a problem.
