### ISSUE TITLE
Supreme issue

### ISSUE THREAD

**Issue by 1232154pp4749687** [yasserqureshi1/Sneaker-Monitors#22]
When I try to build it on Heroku, this is the error I get:
![image](https://user-images.githubusercontent.com/18583466/101243182-4f95bc80-36f6-11eb-80c4-e8cda344d601.png)

**Comment by yasserqureshi1** [comment]
Sorry for the late response. I will be looking into this error.

**Comment by yasserqureshi1** [comment]
I've made some changes, please try again with the new updates. If it still doesn't work, please send me the log file and any further details with the issue.
