### ISSUE TITLE
error: Microsoft Visual C++ 14.0 is required

### ISSUE THREAD

**Issue by Freezen2** [yasserqureshi1/Sneaker-Monitors#23]
![image](https://user-images.githubusercontent.com/65622611/101288721-599fe400-37f8-11eb-8636-630dac8c4fff.png)
![image](https://user-images.githubusercontent.com/65622611/101288735-73d9c200-37f8-11eb-99a4-58071ab0de9f.png)

**Comment by yasserqureshi1** [comment]
You need to install the visual c++ build tools. You can do this through the following link:

https://visualstudio.microsoft.com/visual-cpp-build-tools/
