### ISSUE TITLE
Apply it on Brazil SNKRS sites

### ISSUE THREAD

**Issue by lzcampos** [yasserqureshi1/Sneaker-Monitors#25]
Hi!

I'm from Brazil! I liked your project and I think it would be useful here. I'll be glad to contribute with the project.

**Comment by yasserqureshi1** [comment]
> Hi!
> 
> 
> 
> I'm from Brazil! I liked your project and I think it would be useful here. I'll be glad to contribute with the project.

Hi. Thank you for the suggestion. Feel free to contribute by forking the project and making a Pull Request. I usually use a very standard format when creating my monitors. I'll create a template soon, but for now have a look at the code that is already uploaded. I look forward to seeing your monitors!

**Comment by lzcampos** [comment]
Okay, thanks! I will update you next days.

**Comment by bruno-zaccariello** [comment]
@yasserqureshi1 I can help develop to brazilian location, is there a discord server or any other way that I can contact you ? 

I need to understand more about the API and the code :)

**Comment by lzcampos** [comment]
Of course! You can add me on discord: LuizEDC #9139

**Comment by Codeff3** [comment]
@lzcampos Were you able to make the request with Nike BR? how does this need some link from an API?

**Comment by lzcampos** [comment]
No, I didn't found the API end point in the BR server yet... I'm still searching, because crawling it don't looks like the best solution

**Comment by yasserqureshi1** [comment]
> Of course! You can add me on discord: LuizEDC #9139

Hi, there's a discord server. You can join here: https://discord.gg/7qYH6wTp

**Comment by yasserqureshi1** [comment]
New update has Brazil site
