### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by ethan2k5** [yasserqureshi1/Sneaker-Monitors#26]
When i type in "pip install -r requirements.txt" it says that pip is not a known command ?

**Comment by yasserqureshi1** [comment]
This means you do not have pip installed on your system. This website details how to install pip: https://pip.pypa.io/en/stable/installing/

Essentially first you need to download pip using the command in Terminal or Command Prompt:
`curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py`

Then navigate to the directory in which it is downloaded (should be downloaded in the directory already open) and depending on your system, run the specific command:
- Windows: `py get-pip.py`
- Unix/Mac: `python get-pip.py`

There is a lot of documentation and many YouTube tutorials that cover this. Hope this helps.
