### ISSUE TITLE
Multiple Proxies

### ISSUE THREAD

**Issue by Lukemul6** [yasserqureshi1/Sneaker-Monitors#29]
I added a proxy, but is there a format to add multiple lines of proxies?

**Comment by yasserqureshi1** [comment]
Currently no support for multiple proxies. I may add this feature in the future so will keep this issue open.

**Comment by Lukemul6** [comment]
Sounds good, is there a way we can verify that proxies are actually working? I just put one of my paid proxies in and let it run and it was running perfectly fine now my main IP is banned from the site and the bot no longer works, even if I change out the proxies lol

**Comment by yasserqureshi1** [comment]
> Sounds good, is there a way we can verify that proxies are actually working? I just put one of my paid proxies in and let it run and it was running perfectly fine now my main IP is banned from the site and the bot no longer works, even if I change out the proxies lol

Sorry I didn't see this issue. I've just updated the monitors with support for multiple proxies and a rotating user-agent. Possibly to stop it getting banned you can increase the delay.
