### ISSUE TITLE
Place important variables in a .env file instead of in the code

### ISSUE THREAD

**Issue by delivey** [yasserqureshi1/Sneaker-Monitors#3]
Hey, I noticed a lot of the instructions for running bots look like this:
`Insert a name for your bot on line 64`

I think ease of usability for this could be greatly improved if we used a .env file, pushed, and then added to .gitignore so people wouldn't accidentally push their credentials

I have experience working with the [python dotenv module](https://pypi.org/project/python-dotenv/), so if you'd assigned me to this I could do it.

**Comment by yasserqureshi1** [comment]
I normally use a config.py file and add that to the .gitignore file. Thanks for this though!
