### ISSUE TITLE
Suggestion instead of Issues

### ISSUE THREAD

**Issue by shifaul98** [yasserqureshi1/Sneaker-Monitors#31]
Hey!

I totally appreciate you with giving this plug. Just a suggestion: put the size and the price when tracking items from SNKRS. That'll be dope. 

Thanks and cheers!

**Comment by Lukemul6** [comment]
I second this :D

**Comment by mericausa** [comment]
Third. This would be great!

**Comment by yasserqureshi1** [comment]
Hi. Thanks for the suggestion. I'll give this a go, but it is very tricky. Note that I may not be able to do this with all the monitors

**Comment by yasserqureshi1** [comment]
This has been added. Sorry for the late response
