### ISSUE TITLE
Getting syntax error with proxy on all scripts

### ISSUE THREAD

**Issue by mikehenriquezf** [yasserqureshi1/Sneaker-Monitors#33]
Hello there, i was trying to test this script, and noticed that im getting this error on all scripts, im i missing something? Thanks!

➜  Supreme python SupremeMonitor.py
  File "SupremeMonitor.py", line 23
    self.proxy = { f"http://{proxy}" }
                                   ^
SyntaxError: invalid syntax
➜  Supreme

**Comment by mikehenriquezf** [comment]
my mistake

**Comment by yasserqureshi1** [comment]
No worries. if you have any other issues, post them in and I'll try sort them out as soon as I can
