### ISSUE TITLE
Shopify only checking for changes to current products and no new products?

### ISSUE THREAD

**Issue by DarylRob** [yasserqureshi1/Sneaker-Monitors#34]
I've had the monitor running for one site and getting no notifications whilst comparing it to another cook group with monitors, there's notifications for the site coming in. 

from glancing at the code, could it be we're looking just for changes without additions?

**Comment by yasserqureshi1** [comment]
> I've had the monitor running for one site and getting no notifications whilst comparing it to another cook group with monitors, there's notifications for the site coming in. 
> 
> 
> 
> from glancing at the code, could it be we're looking just for changes without additions?

Thanks for the message. Yes the code does look for changes but it also should check if the product is a new product. I'll look into why this is the case.

**Comment by yasserqureshi1** [comment]
Which Shopify site are you trying to monitor?

**Comment by DarylRob** [comment]
hanon-shop.com

**Comment by yasserqureshi1** [comment]
> hanon-shop.com

I've rewritten the monitor and performed some tests - should be working now. Open a new issue if this is not the case.
