### ISSUE TITLE
problem with the discord webhook

### ISSUE THREAD

**Issue by Dynamomaster** [yasserqureshi1/Sneaker-Monitors#37]
test = SNKRSMonitor(webhook=CONFIG['https://discord.com/api/webhooks/796349146918420513/mvwrJaAGwKEhLjLZ7bG3g7Rg5BGVoYxyhp_PiGtu4X87S7FQTuo_U9IStiMw4Qen-NZC'], loc=CONFIG['GB'], lan=CONFIG['en-GB'], proxy=CONFIG[''])     
   
KeyError: 
'https://discord.com/api/webhooks/796349146918420513/mvwrJaAGwKEhLjLZ7bG3g7Rg5BGVoYxyhp_PiGtu4X87S7FQTuo_U9IStiMw4Qen-NZC'

**Comment by yasserqureshi1** [comment]
> test = SNKRSMonitor(webhook=CONFIG['https://discord.com/api/webhooks/796349146918420513/mvwrJaAGwKEhLjLZ7bG3g7Rg5BGVoYxyhp_PiGtu4X87S7FQTuo_U9IStiMw4Qen-NZC'], loc=CONFIG['GB'], lan=CONFIG['en-GB'], proxy=CONFIG[''])
> 
> KeyError:
> 'https://discord.com/api/webhooks/796349146918420513/mvwrJaAGwKEhLjLZ7bG3g7Rg5BGVoYxyhp_PiGtu4X87S7FQTuo_U9IStiMw4Qen-NZC'

You have to put those variables in the .env file instead of putting them in the Python file. There should be no need to edit the python file.
