### ISSUE TITLE
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.

### ISSUE THREAD

**Issue by Frostelic** [yasserqureshi1/Sneaker-Monitors#38]
I have a problem there is standing : DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.

I have Python 3.9.1
Please help.

**Comment by yasserqureshi1** [comment]
So this can be due to your Python 3.9 not being in your environment variables.  Try the recommendations on this link: https://stackoverflow.com/questions/18058389/how-to-switch-between-python-2-7-to-python-3-from-command-line/18059129
