### ISSUE TITLE
Sneaker Monitor

### ISSUE THREAD

**Issue by Blarshdeep** [yasserqureshi1/Sneaker-Monitors#41]
Hey man, having an issue after 'pip install -r requirements.txt'
![issue](https://user-images.githubusercontent.com/64309738/105034922-1186fa80-5a0f-11eb-9a50-1f6abe606fc3.PNG)

**Comment by yasserqureshi1** [comment]
You need to upgrade Microsoft Visual C++. Follow the link it returned and it should explain next steps.
