### ISSUE TITLE
Shopify Monitor Bulk Notifications

### ISSUE THREAD

**Issue by DarylRob** [yasserqureshi1/Sneaker-Monitors#44]
Hi mate, back again. 

Just wondering on the new shopify monitor it's sent about 30 notifications all at once. 

I'm monitoring hanon-shop and I'm looking at other monitors at the same time and none of them seem to do this. Trying to go through the code, seems like when its checking the json against itself, it's finding a load of differences all at once??

**Comment by yasserqureshi1** [comment]
The monitors look for changes in the site and sent a notification once a change is detected. I guess the changes were detected at the same time so sent a bunch together. I'll keep this issue open and check whether this is an issue or if it had just detected 30 changes at once.

**Comment by yasserqureshi1** [comment]
I believe I have fixed this issue with the current update
