### ISSUE TITLE
Stuck on "Sending notification to Discord..."

### ISSUE THREAD

**Issue by VeryClearChemist** [yasserqureshi1/Sneaker-Monitors#47]
Code seems to not move on from "Sending notification to Discord..." Been waiting for roughly 20min now. Any Fixed?

**Comment by VeryClearChemist** [comment]
I should add that nothing is appearing on discord as well

**Comment by yasserqureshi1** [comment]
That's normal. It starts the monitor and changes on the site are detected and sent.
