### ISSUE TITLE
SNKRS monitor issue

### ISSUE THREAD

**Issue by Lukemul6** [yasserqureshi1/Sneaker-Monitors#48]
Snkrs log is constantly sending this error
```
Error -  'str' object has no attribute 'items'
```

Any idea?

**Comment by mericausa** [comment]
I get the same error 😦

**Comment by yasserqureshi1** [comment]
> Snkrs log is constantly sending this error
> 
> ```
> Error -  'str' object has no attribute 'items'
> ```
> 
> Any idea?


Which location are you using the SNKRS monitor?

**Comment by Lukemul6** [comment]
The one that was already on there

```
LOCATION = "GB"
LANGUAGE = "en-GB"
```

**Comment by yasserqureshi1** [comment]
> The one that was already on there
> 
> ```
> LOCATION = "GB"
> LANGUAGE = "en-GB"
> ```

How are you running it? On your local machine or on a VPS?

**Comment by Lukemul6** [comment]
Local machine

**Comment by Lukemul6** [comment]
Could it be the proxies?

**Comment by yasserqureshi1** [comment]
> Could it be the proxies?

Possibly. I will look into this and will update you hopefully by tomorrow.

**Comment by Lukemul6** [comment]
Okay sure thanks!

**Comment by breckenridmj** [comment]
ERROR: Failed building wheel for multidict
Failed to build multidict
ERROR: Could not build wheels for multidict which use PEP 517 and cannot be installed directly

Help please?

**Comment by yasserqureshi1** [comment]
This should have been solved with the last update. Open this issue again or create a new one if this occurs again

**Comment by hardt0303** [comment]
Error -  'str' object has no attribute 'items'

Im getting this error using US 

# This is your location code according to Location-Code-List.md
LOCATION = "US"

# --------------------- SNKRS BOT FEATURES ---------------------
LOC = "US"
LAN = "en-US"

**Comment by yasserqureshi1** [comment]
> Error - 'str' object has no attribute 'items'
> 
> Im getting this error using US
> 
> # This is your location code according to Location-Code-List.md
> LOCATION = "US"
> 
> # --------------------- SNKRS BOT FEATURES ---------------------
> LOC = "US"
> LAN = "en-US"

The language code for US is just "en"
