### ISSUE TITLE
Monitor setup bug

### ISSUE THREAD

**Issue by sneakerxwars** [yasserqureshi1/Sneaker-Monitors#49]
requirements file not working

root@vps66937 [/home/sneake28/mon1/Sneaker-Monitors]# pip install -r requirements.txt
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==21.0.1', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/site-packages/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")

**Comment by sneakerxwars** [comment]
Same thing as non root user.

On Cent OS

**Comment by yasserqureshi1** [comment]
> Same thing as non root user.
> 
> 
> 
> On Cent OS

**Comment by yasserqureshi1** [comment]
> requirements file not working
> 
> 
> 
> 
> 
> root@vps66937 [/home/sneake28/mon1/Sneaker-Monitors]# pip install -r requirements.txt
> 
> Traceback (most recent call last):
> 
>   File "/usr/bin/pip", line 9, in <module>
> 
>     load_entry_point('pip==21.0.1', 'console_scripts', 'pip')()
> 
>   File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
> 
>     return get_distribution(dist).load_entry_point(group, name)
> 
>   File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
> 
>     return ep.load()
> 
>   File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
> 
>     entry = __import__(self.module_name, globals(),globals(), ['__name__'])
> 
>   File "/usr/lib/python2.7/site-packages/pip/_internal/cli/main.py", line 60
> 
>     sys.stderr.write(f"ERROR: {exc}")
> 
> 

You are using Python2.7 when you should use Python3+ (written in Python3.8)

**Comment by sneakerxwars** [comment]
Thank you. 

yum -y install python3-pip && pip3 ... solved the trick.
