### ISSUE TITLE
Nothing gets sent on discord (for SNKRS and Footsites)?

### ISSUE THREAD

**Issue by Lukemul6** [yasserqureshi1/Sneaker-Monitors#5]
Hey I added my webhook on both footsites and SNKRs and I have had then running for about 8 hours now, I can see the logs saying successfully scraped site etc but in the 8 hours there has been nothing coming through on my webhooks. I checked a SNKRs monitor in a group I am in and they have had several posts today. Any idea?

**Comment by yasserqureshi1** [comment]
Thanks for letting me know. I'll have a look into this. So you are saying that the SNKRS monitor did not send a notification when it should (backed by other monitors)? What about the Footlocker one - did that not send a notification when it should've?

**Comment by yasserqureshi1** [comment]
> Hey I added my webhook on both footsites and SNKRs and I have had then running for about 8 hours now, I can see the logs saying successfully scraped site etc but in the 8 hours there has been nothing coming through on my webhooks. I checked a SNKRs monitor in a group I am in and they have had several posts today. Any idea?

Thanks for letting me know. I'll have a look into this. So you are saying that the SNKRS monitor did not send a notification when it should (backed by other monitors)? What about the Footlocker one - did that not send a notification when it should've?

**Comment by Lukemul6** [comment]
Neither footlocker or SNKRS sent anything. Is it supposed to say anything in the command line after "STARTING MONITOR"? I have a footsites US monitor but I have to manually add SKUs to it so I wasnt sure if I had to do the same for this?

**Comment by yasserqureshi1** [comment]
> Neither footlocker or SNKRS sent anything. Is it supposed to say anything in the command line after "STARTING MONITOR"? I have a footsites US monitor but I have to manually add SKUs to it so I wasnt sure if I had to do the same for this?

These monitors will notify you on ANY changes on the site. The Footlocker monitor, so far, only updates releases (not restocks). When it's sending a notification, it then prints the notification in the console. I'll have a look into these issues, and will let you know what happens. This will take a few days.

**Comment by molokopluss** [comment]
i have the same problem with SNKRS, any fix ?

**Comment by yasserqureshi1** [comment]
Please try the monitor now - we have recently updated our monitors and continue to try to resolve issues. If you still have issues, please reopen an issue. You could try use a proxy if you are hosting this on a server, as we have recently added proxy support.
