### ISSUE TITLE
Trouble installing

### ISSUE THREAD

**Issue by breckenridmj** [yasserqureshi1/Sneaker-Monitors#50]
ERROR: Failed building wheel for multidict
Failed to build multidict
ERROR: Could not build wheels for multidict which use PEP 517 and cannot be installed directly

**Comment by yasserqureshi1** [comment]
> ERROR: Failed building wheel for multidict
> Failed to build multidict
> ERROR: Could not build wheels for multidict which use PEP 517 and cannot be installed directly

See issue #23
