### ISSUE TITLE
errors after running snkr monitor

### ISSUE THREAD

**Issue by tmiller027460** [yasserqureshi1/Sneaker-Monitors#53]
I get the code 204 like everything is running fine.. even get the start message in the discord. Then in the cmd prompt I get

Error - 'objects'

Is this having to do witht the proxy not working?

**Comment by hardt0303** [comment]
Im getting the same error

**Comment by hardt0303** [comment]
After I removed the proxies I get 

Error -  'objects'

**Comment by yasserqureshi1** [comment]
I found this error occurred when the monitor was not set up with the right proxy. Please check whether the proxy location is set to your region. If you still have this error, please reopen this issue. Thanks
