### ISSUE TITLE
error - 'objects'

### ISSUE THREAD

**Issue by Lukegod2000** [yasserqureshi1/Sneaker-Monitors#54]
Keep getting this error I've checked the location and it hasn't changed. I was thinking it was possibly the delay but still doesn't work

**Comment by Lukegod2000** [comment]
Still have the issue but still sends restocks so I have know idea

**Comment by Lukegod2000** [comment]
<string> error on Mac but not Windows

**Comment by ade5791** [comment]
How did you fix this error on windows

**Comment by Lukegod2000** [comment]
> How did you fix this error on windows

Works fine on my windows pc but not my Mac

**Comment by Lukegod2000** [comment]
> How did you fix this error on windows

Turned my windows pc off and on and it worked. But the exact same code doesn’t work on my Mac

**Comment by yasserqureshi1** [comment]
Which monitor is this?

**Comment by Lukegod2000** [comment]
> Which monitor is this?

SNKRS UK

**Comment by yasserqureshi1** [comment]
Try the updated code. This may help. Reopen this issue if it still persists
