### ISSUE TITLE
Footlocker US Error

### ISSUE THREAD

**Issue by cok724** [yasserqureshi1/Sneaker-Monitors#57]
Hey! First I want to say that I appreciate you putting this on github. I got the Supreme monitor working and I know Footsites says it's currently only working okay. I just wanted to report that in the cmd, it is saying "There was an error - main site - 'src' ". I tried a couple of different proxies and my delay is set at 5, just wondering if this is something that you were working on or if its something you know about that I'm doing wrong on my end. Thanks!

**Comment by ade5791** [comment]
Hi Cok74, how were you able to fix the shopify monitor, care to share?

**Comment by yasserqureshi1** [comment]
The US Footlocker site has changed and will need updating. This may take a while

**Comment by ade5791** [comment]
Okay I will keep up with the update. Thanks for this

**Comment by yasserqureshi1** [comment]
I believe the monitor should be working. Others based in the US have helped to sort this out.

**Comment by cok724** [comment]
Very cool, thank you so much for the update!
