### ISSUE TITLE
There was an Error - main site - 'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by Lukegod2000** [yasserqureshi1/Sneaker-Monitors#58]
Getting this error once I run the FootlockerUK

**Comment by yasserqureshi1** [comment]
> Getting this error once I run the FootlockerUK

Thanks for raising this. Could you let me know if you made any edits to the code and what parameters you added to the .env file

**Comment by Lukegod2000** [comment]
> > Getting this error once I run the FootlockerUK
> 
> Thanks for raising this. Could you let me know if you made any edits to the code and what parameters you added to the .env file

I’ve added the Webhook

**Comment by yasserqureshi1** [comment]
I believe this was fixed in the new update. Please reopen this issue if not.
