### ISSUE TITLE
SNKRS - Monitor expecting value: line 1 column 1

### ISSUE THREAD

**Issue by ade5791** [yasserqureshi1/Sneaker-Monitors#63]
see logs

![image](https://user-images.githubusercontent.com/38266156/109748184-6c7f4600-7ba6-11eb-9090-89efea3c9ae4.png)

seem to be a proxy issue as well. Please take a look when you have a chance

**Comment by yasserqureshi1** [comment]
What parameters have you set? i.e. language, location, proxy etc.

**Comment by ade5791** [comment]
Getting forbiden error on the sneaker api url, which that could be the reason why it isn't working? what could be the possible solution for this?

https://api.nike.com/product_feed/threads/v2/?anchor={anchor}&count=60&filter=marketplace(us)&filter=language(en)&filter=channelId(010794e5-35fe-4e32-aaff-cd2c74f89d61)&filter=exclusiveAccess(true%2Cfalse)&fields=active%2Cid%2ClastFetchTime%2CproductInfo%2CpublishedContent.nodes%2CpublishedContent.subType%2CpublishedContent.properties.coverCard%2CpublishedContent.properties.productCard%2CpublishedContent.properties.products%2CpublishedContent.properties.publish.collections%2CpublishedContent.properties.relatedThreads%2CpublishedContent.properties.seo%2CpublishedContent.properties.threadType%2CpublishedContent.properties.custom%2CpublishedContent.properties.title

**Comment by yasserqureshi1** [comment]
> Getting forbiden error on the sneaker api url, which that could be the reason why it isn't working? what could be the possible solution for this?
> 
> [https://api.nike.com/product_feed/threads/v2/?anchor={anchor}&count=60&filter=marketplace(us)&filter=language(en)&filter=channelId(010794e5-35fe-4e32-aaff-cd2c74f89d61)&filter=exclusiveAccess(true%2Cfalse)&fields=active%2Cid%2ClastFetchTime%2CproductInfo%2CpublishedContent.nodes%2CpublishedContent.subType%2CpublishedContent.properties.coverCard%2CpublishedContent.properties.productCard%2CpublishedContent.properties.products%2CpublishedContent.properties.publish.collections%2CpublishedContent.properties.relatedThreads%2CpublishedContent.properties.seo%2CpublishedContent.properties.threadType%2CpublishedContent.properties.custom%2CpublishedContent.properties.title](https://api.nike.com/product_feed/threads/v2/?anchor=%7Banchor%7D&count=60&filter=marketplace(us)&filter=language(en)&filter=channelId(010794e5-35fe-4e32-aaff-cd2c74f89d61)&filter=exclusiveAccess(true%2Cfalse)&fields=active%2Cid%2ClastFetchTime%2CproductInfo%2CpublishedContent.nodes%2CpublishedContent.subType%2CpublishedContent.properties.coverCard%2CpublishedContent.properties.productCard%2CpublishedContent.properties.products%2CpublishedContent.properties.publish.collections%2CpublishedContent.properties.relatedThreads%2CpublishedContent.properties.seo%2CpublishedContent.properties.threadType%2CpublishedContent.properties.custom%2CpublishedContent.properties.title)

Just checking whether this has been resolved with current updates?

**Comment by yasserqureshi1** [comment]
No update, so closing issue.
