### ISSUE TITLE
Monitors not working from my server in Mumbai

### ISSUE THREAD

**Issue by amitavroy** [yasserqureshi1/Sneaker-Monitors#67]
Hi, I am trying to run the monitors on my local machine and work with the webhook notification so that my application can ingest that webhook information and accordingly react.

However, I am not getting any webhook notification apart from the initial one which shows the success message.

Do I need any proxy setup or something for it to get to work?

**Comment by Thjisio** [comment]
Hi,

Please check your logs since you might get blocked by anti-bot on some websites.

**Comment by yasserqureshi1** [comment]
> Hi, I am trying to run the monitors on my local machine and work with the webhook notification so that my application can ingest that webhook information and accordingly react.
> 
> However, I am not getting any webhook notification apart from the initial one which shows the success message.
> 
> Do I need any proxy setup or something for it to get to work?

Just checking whether this has been resolved with current updates?

**Comment by yasserqureshi1** [comment]
No update, so closing issue
