### ISSUE TITLE
Supreme Monitor: Error using with server

### ISSUE THREAD

**Issue by Dark-Ale27** [yasserqureshi1/Sneaker-Monitors#69]
Why when I run the SupremeMonitor.py locally there's no problem but when I run it on a server after saying it sent the notification to discord it says: Exception found 'Expecting value: line 2 column 1 (char 1)' - Rotating proxy and user-agent   ???  I've also updated line 134 & 161 as said by kacperkwapisz.

**Comment by elypsis** [comment]
Ive also got same problem when running on an aws ubuntu instant but works fine on Mac. (both have same version of python 3.8). Some of the other bots work fine on AWS.

**Comment by 808enterprisellc** [comment]
i'm getting the same error for Supreme, just input my webhook.  I put in an ip auth proxy in your format with the : in between and still getting the same error. Nothing else is changed  help!!

**Comment by yasserqureshi1** [comment]
I believe that Supreme requires residential proxies. Not 100% sure about this though. I do have trouble hosting this on a server as well, so will continue to look into this.

**Comment by yasserqureshi1** [comment]
I was told that if you run it via tor, it works
