### ISSUE TITLE
JD Sports with Shopify Monitor

### ISSUE THREAD

**Issue by lwangx123** [yasserqureshi1/Sneaker-Monitors#70]
Im' using shopify with this website https://www.jdsports.my/men/?facet-new=latest&max=72 and getting this error

**Comment by lwangx123** [comment]
# --------------------- WEBHOOR URL ---------------------
WEBHOOK = ""

# --------------------- LOCATION ---------------------
# This is your location code according to Location-Code-List.md
LOCATION = "MY"

# --------------------- SHOPIFY URL ---------------------
# Insert the url of the Shopify store here. Ensure that it points to /products.json
# E.G. URL = "https://www.hanon-shop.com/collections/whats-new/products.json"
URL = "https://www.jdsports.my/men/?facet-new=latest/products.json"

# --------------------- DELAY ---------------------
# This is the delay between checks. If you start to get error messages, it's best to increase this.
# Measured in seconds
DELAY = 1

# --------------------- OPTIONAL PROXY ---------------------
# Proxies must follow this format: "<proxy>:<port>" OR "<proxy_username>:<proxy_password>@<proxy_domain>:<port>")
# If you want to use multiple proxies, please seperate multiple proxies using "%".
# E.G. PROXY = "proxy1:proxy1port%proxy2:proxy2port"
PROXY = ""

# --------------------- OPTIONAL KEYWORDS ---------------------
# Each keyword should be a separate multiple keywords using "%"
# E.G. KEYWORDS = "box%logo"
KEYWORDS = ""

# --------------------- DISCORD BOT FEATURES ---------------------
USERNAME = "Shopify Monitor"
AVATAR_URL = "https://cdn3.iconfinder.com/data/icons/popular-services-brands-vol-2/512/shopify-512.png"
COLOUR = 15258703

**Comment by yasserqureshi1** [comment]
JD Sports is not a Shopify site
