### ISSUE TITLE
Brazilian Set-up

### ISSUE THREAD

**Issue by Codeff3** [yasserqureshi1/Sneaker-Monitors#71]
how do I do pro monitor work in Brazil I need some link from nike API?

**Comment by Thjisio** [comment]
Hi,

You need an API link. Besides that, the developer has not looked in to the framework of NIKE Brazil, so there might be more recoding needed for it to actually function for that region.

**Comment by yasserqureshi1** [comment]
Closing as this is a duplicate of #25
