### ISSUE TITLE
SNKRSMonitor sending incorrect links to US users (with fix)

### ISSUE THREAD

**Issue by smacoun** [yasserqureshi1/Sneaker-Monitors#75]
Users with "US" location selected in line 9 of "Sneaker-Monitors/SNKRS/.env" as seen below:

"LOC = "US"   

Receive broken links for Nike products when the monitor posts to discord.  

I noticed that the monitor is appending "/US" to the links after nike.com as seen in the example below:

https://www.nike.com/US/launch/t/air-force-1-07-mens-shoe-5QFp5Z (broken link sent by monitor)
https://www.nike.com/launch/t/air-force-1-07-mens-shoe-5QFp5Z (proper working link)

The online Nike store for the US does not use a location code like other countries.  

I found a fix for this by editing line line 75 of "SNKRSMonitor.py" and removing "/{CONFIG["LOC"]}" as seen below:

embed["url"] = f'https://www.nike.com/{CONFIG["LOC"]}/launch/t/' + slug              (original code)
embed["url"] = f'https://www.nike.com/launch/t/' + slug                                          (edit for proper US SNKRS links)

I hope you find this "fix" for US users helpful.  Thank you for sharing such a well thought out project.

**Comment by yasserqureshi1** [comment]
Thank you for pointing this out! I'll mention this in the documentation
