### ISSUE TITLE
supreme monitor can't send webhook

### ISSUE THREAD

**Issue by poipoiuuu** [yasserqureshi1/Sneaker-Monitors#76]
I want to use the monitor at supreme in Japan.
However, the webhook is not sending properly.

![155556](https://user-images.githubusercontent.com/81848570/113471120-3549d080-9495-11eb-86a0-87ab944ac8f2.png)

**Comment by Thjisio** [comment]
Hi,

You are using Japanese characters which can't be encoded hence it's throwing an error.

Kind regards,
