### ISSUE TITLE
only input webhook and 1 proxy getting rotating/user agent payload runs

### ISSUE THREAD

**Issue by 808enterprisellc** [yasserqureshi1/Sneaker-Monitors#78]
Thats the only thing I changed and input since I"m on a server and the server ip is banned on supreme.  These proxies work as I use them on supreme all the time.  What am I doing wrong?

**Comment by Thjisio** [comment]
Hi,

The proxies are not banned. Supreme is throwing 403 when you run the monitor on the server because it forbids access.

Kind regards,

**Comment by yasserqureshi1** [comment]
This is a duplicate of #69 so will close this.
