### ISSUE TITLE
Requests for Soleboxmonitor.py

### ISSUE THREAD

**Issue by E184728R** [yasserqureshi1/Sneaker-Monitors#83]
Since your recent commit about 10 minutes, i have this error for the Soleboxmonitor.py ; 
 Traceback (most recent call last):
  File "C:\Users\charly\Desktop\Sneaker-Monitors-master\Demandware\Solebox\SoleboxMonitor.py", line 1, in <module>
    from random_user_agent.params import SoftwareName, HardwareType
ModuleNotFoundError: No module named 'random_user_agent'
Is it normal ?

thanks in advance ;)

**Comment by yasserqureshi1** [comment]
Hi,

This means that you have not installed the dependencies. To do this use the command:
```
pip -r install requirements.txt
```
