### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by dullie2x** [yasserqureshi1/Sneaker-Monitors#84]
Hey, I keep getting a key error for line 42 in the code. 

#  for item in output['objects']:
KeyError: 'objects'

**Comment by yasserqureshi1** [comment]
> Hey, I keep getting a key error for line 42 in the code. 
> 
> 
> 
> #  for item in output['objects']:
> 
> KeyError: 'objects'

Could you clarify which monitor you are using?

**Comment by dullie2x** [comment]
hey, im using SNKRS

**Comment by yasserqureshi1** [comment]
This usually occurs if the location and language codes are not set up correctly. Please refer to https://yasserqureshi1.github.io/Sneaker-Monitors/params.html#snkrs
