### ISSUE TITLE
FootlockerAUMonitor

### ISSUE THREAD

**Issue by JunJie00000** [yasserqureshi1/Sneaker-Monitors#96]
![image](https://user-images.githubusercontent.com/50447897/121992269-e0e79900-cdd3-11eb-91a5-17c76662e50c.png)

Having this issue when I start FootlockerAU monitor. Tried with both local and proxy and still facing same issue

**Comment by yasserqureshi1** [comment]
I've made adjustments to the monitor. Give it a go and reopen the issue if it still persists
